### ISSUE TITLE
Aptomi keeps creating new policy generations + possible race

### ISSUE THREAD

**Issue by ralekseenkov** [Aptomi/aptomi#198] opened 2017-11-29 09:18 UTC
1. Policy was already pre-populated (not sure about the state)

2. Aptomi keeps creating new policy generations when you feed the same policy over API

```
[aptomi] aptomictl policy apply --username Sam -f examples/03-twitter-analytics/policy                                 19:03:17  ☁  master ☂ 𝝙 ⚡ ✭ 𝝙
&{{policy-update-result} 15 [action-component-update/cluster-us-east#main#twitter_stats#prod#tweeviz action-component-update/cluster-us-east#main#twitter_stats#prod#root action-component-endpoints/cluster-us-east#main#twitter_stats#prod#tweeviz action-post-process/]}

[aptomi] aptomictl policy apply --username Sam -f examples/03-twitter-analytics/policy                                 19:03:17  ☁  master ☂ 𝝙 ⚡ ✭ 𝝙
&{{policy-update-result} 16 [action-component-update/cluster-us-east#main#twitter_stats#prod#root action-component-update/cluster-us-east#main#twitter_stats#prod#tweeviz action-component-endpoints/cluster-us-east#main#twitter_stats#prod#tweeviz action-post-process/]}

[aptomi] aptomictl policy apply --username Sam -f examples/03-twitter-analytics/policy                                 19:03:17  ☁  master ☂ 𝝙 ⚡ ✭ 𝝙
&{{policy-update-result} 17 []}

[aptomi] aptomictl policy apply --username Sam -f examples/03-twitter-analytics/policy                                 19:03:17  ☁  master ☂ 𝝙 ⚡ ✭ 𝝙
&{{policy-update-result} 18 []}

...

[aptomi] aptomictl policy apply --username Sam -f examples/03-twitter-analytics/policy                                 19:03:17  ☁  master ☂ 𝝙 ⚡ ✭ 𝝙
&{{policy-update-result} 42 []}

[aptomi] aptomictl policy apply --username Sam -f examples/03-twitter-analytics/policy                                 19:03:17  ☁  master ☂ 𝝙 ⚡ ✭ 𝝙
&{{policy-update-result} 43 []}
```

3. A separate problem is -- note policy generations #15 and #16. Managed to create them somehow with two consecutive API calls (less
   than a second between them). Seems like this situation should be impossible (diff is the same really). May be there is a major bug with
   saving/updating desired state somewhere. Or a race condition.

4. Once fixed, can we PLEASE add a unit test, which will specifically check that policy update is correctly
   handled and no duplicate policies are being produced?

**Comment by Frostman** [comment] 2017-12-03 21:10
The root cause of this bug was duplicate prod dependency objects after changing version in initial one using sed (that created new file with -changed- in name). Fixed by adding validation for duplicate objects in both API and CLI

**Closed by Frostman** 2017-12-03 21:10 UTC
Labels: bug, high
