### ISSUE TITLE
Apply fails if delete full policy

### ISSUE THREAD

**Issue by Frostman** [Aptomi/aptomi#201] opened 2017-12-09 05:21 UTC
Steps to reproduce:

`
aptomictl policy apply --username Sam -f examples/03-twitter-analytics/policy/
aptomictl policy delete --username Sam -f examples/03-twitter-analytics/policy/
`

**Comment by ralekseenkov** [comment] 2017-12-10 14:13
the root cause of the problem is that we are deleting policy objects from the desired policy, while
we still have running component instances referring to them. then, when we are trying to delete component
instances, the following happens:
- in order to delete a component, we need to know
  - component instance (can always we looked up in the actual state)
  - service.component.Code.Type (not-existent in desired policy)
  - cluster (not-existent in desired policy)

the workaround would be to delete all dependencies first and then delete the rest of the objects.

we still have to discuss what happens if we are deleting clusters and services, but still have component
instances pointing them. not allowing to delete?


misc issues fixed so far:
1. the notion we invented called "actual policy" is not really valid. actual state gets updated all the time
  and may contain components coming from different policy generations (e.g. services etc). so there is no
  such a single thing called "actual policy". I deleted it from the code of the enforcer, applier and actions.

2. actual state does not contain DependencyInstanceMap and ComponentProcessingOrder in the store. so I had to
  change the code, so it panics in case we try to access these in actual state

3. the code for updating actual state was copy/pasted across actions, which made it hard to debug. extracted it
  into a separate place and reused across actions

**Comment by ralekseenkov** [comment] 2017-12-13 10:58
Fixed by adding validation. With the latest set of changes, delete all dependencies first:
```aptomictl policy delete -u Sam -f 'examples/03-twitter-analytics/policy/*-ts.yaml'``` (note single quotes)

Then delete the rest of the objects:
```aptomictl policy delete -u Sam -f examples/03-twitter-analytics/policy```

**Closed by ralekseenkov** 2017-12-13 10:58 UTC
Labels: bug, high
